### PR TITLE
@libc++: Fix CMake build errors, remove @libc++abi

### LINKED ISSUE #2: Error building @libc++abi
This is the error I got when trying to build `@libc++abi`.
```
CMake Error at CMakeLists.txt:4 (message):
  libc++abi now requires being built in a monorepo layout with libcxx
  available
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2.

After doing research I learned that the following structure is required in order to build `libc++abi` and `libc++`:
```
<build_dir>/
    libcxx/
    libcxxabi/
    llvm/
```
`libc++abi` complains if `libcxx/` doesn't exist, and `libc++` complains if `libcxxabi/` and `llvm/` don't both exist.

Since `libc++abi` and `libc++` depend on each other's existence in order to build, I determined it would be best if they were just merged into one package.

Maybe this could be improved upon since it requires also downloading `llvm` seemingly just to pass a few checks, but this works as it is.

I will never get why LLVM thinks having a monorepo is a good idea.

---

Here's some relevant links showing where the issues I was having were caused:
https://github.com/llvm/llvm-project/commit/19aec8c90492435b1ff59dacd4307f1bbcf6ab1d
https://github.com/llvm/llvm-project/commit/8bc62db272448035d60ca9f31ff67040a288063c

### CODE REVIEW

**Comment by konimex** [comment]
I'm afraid that in the future LLVM 12 (at least we have to see until -rc), the tarball for libc++{,abi}-12 won't even be released so we have to use the monorepo for everything. At least building still works. I'll look into this issue (and if possible come up with a solution, or just merge yours).

Perhaps we can look into using the monorepo download (this one: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-project-11.0.0.tar.xz) recommend "merging" the source cache (e.g. link `$HOME/.cache/kiss/sources/@libc++` to `$HOME/.cache/kiss/sources/llvm`) to save disk space (and Internet bandwidth). I already do this internally (the latter part, before `kiss` changed their cache structure) but yet to recommend it.

**Comment by ghost** [comment]
I would definitely look into it more before you merge this pull request.

This morning I finally finished the full thing, removed `gcc`, and got an error from `libc++` that `libatomic` was missing. I'm not yet sure if I messed something else up but I decided to start from scratch again and pay closer attention.

If I find this has to be done differently I'll close this PR and open a new one with what I did this time around.

**Comment by jedavies-dev** [comment]
I used this repo recently and found the same issue you described.
Added libc++ to the sources of libc++abi.  Added libc++abi and llvm to libc++ sources.
After this I was able to continue and complete the build.

Maybe it makes sense to use the monorepo if LLVM is going that way anyway. Using a trick like konimex mentioned would help reduce the downloads and could be added to the install instructions.

**Comment by ghost** [comment]
Yeah, I figure my issue was likely that I merged the packages and `libc++` didn't use `libc++abi` when building. I'm at `@clang-pass1` right now so we'll see how it goes if I keep them separate and install `libc++abi` first.

As for using the monorepo, wouldn't it be possible to just build the full LLVM twice (using the first pass to build the second pass)? That would make things simpler as there would just be `@llvm-pass1` and `llvm`.

**Comment by ghost** [comment]
Nope, I just finished the process again and `ldd /usr/bin/clang` resulted in `libatomic.so.1`.

Since I have to make another attempt, I'm going to see what I can do with the monorepo as a whole.

**Comment by konimex** [comment]
> As for using the monorepo, wouldn't it be possible to just build the full LLVM twice (using the first pass to build the second pass)? That would make things simpler as there would just be `@llvm-pass1` and `llvm`.

The main problem would be handling `libunwind` and `libc++{,abi}`.

If we build `libunwind` and `libc++{,abi}` inside the monorepo as is, it'll be linked to `libgcc.so`. If we use monorepo `@llvm-pass1`, I'm afraid that when we build `llvm` proper, LLVM binaries will link to old `libc++.so` which links to GCC. We'd end up needing 3 big passes for LLVM instead of 2 (relatively) smaller passes for Clang.

I'm building LLVM now to look for alternative flags possible.

**Comment by konimex** [comment]
Regarding `libc++` linking to `libatomic`, I tracked it to this commit: https://github.com/llvm/llvm-project/commit/e0184357fc781e939f4e4368fc8aff692ce227ed

I've added a flag in https://github.com/konimex/kiss-llvm/commit/ef17b16dc5780affd0e7371dbd9471b3c60c6347 in my monorepo branch, but yet to merge it to master as I'm yet to build the main LLVM repo.

**Comment by ghost** [comment]
Is there any reason why you still have `libelf` as a package? As of August, KISS uses the same `elfutils` implementation and seems to be more up to date (0.182 vs 0.181). The KISS package also doesn't seem to need the same patch that's included here.

https://k1ss.org/blog/20200803a#3.0
https://github.com/kisslinux/repo/tree/master/extra/libelf

**Comment by konimex** [comment]
`elfutils` can't be built with Clang because elfutils enforces a hard GNU99 check, so in the past we used a patched elftoolchain so the new Linux kernel would work with it. @dilyn-corner has discovered a flag that overrides autoconf's gnu99 check so that elfutils (or at least the libelf part) works with Clang no matter what.

I wanted to bring it upstream but was not sure if Dylan would accept it or not, so I added it here first as a backup. Now that it has been merged in https://github.com/kisslinux/repo/blob/91b91bb3e5608e09f914f1e1bf63d1b094d83340/extra/libelf/build#L17 I see no point in including libelf any further (aside of constant warnings since apparently Clang doesn't understand a few warnings.) https://github.com/konimex/kiss-llvm/blob/19439cc2d0cd26c406319e9b7681f18f88df7cf0/libelf/build#L8

**Comment by dilyn-corner** [comment]
I've built the tool chain on this repo multiple times; the `libatomic` error is sporadic; I think it's mostly just due to the tool chain getting tainted - basically impossible to fix (even LFS can have this sort of problem, even with all their precautions for isolating the system). 

There doesn't seem to be a technically proficient way to build this stack perfectly every time on an existing system - I got it build perfectly two times, out of around five or six attempts. 

You could perhaps work *with* the monorepo problem instead of against it; build the entire stack in a single package. It would take bloody ages to compile, and you'd have to set a bunch of variables, but it would save bandwidth if that was the primary concern.

**Comment by konimex** [comment]
Good idea. I've added it to https://github.com/konimex/kiss-llvm/commit/a4d5b372f81e1d69d7e9cf70d7bb0d1e86b4466c (and subsequently removed the separate packages).

But I'd still like to build the final LLVM toolchain as a standalone package rather than part of the bootstrap. This is to avoid rebootstrapping in the event of updates.

I've tested it and it works fine, so I'll need one more tester to see if it's good enough and doesn't link to `libatomic` (this applies to `libc++.so`) before I push the commit to master and close the issue.

**Comment by git-bruh** [comment]
~~I successfully built the monorepo branch a few hours ago (till 9d8f26d3485e7e63aa9af47a19b20ed70150f80f)~~

EDIT: I didn't test the compiler that time, it doesn't actually work for building most packages that add `-static` to the `CFLAGS`  throwing some errors related to undefined symbols (Probably a "me" problem though since I'm using glibc and the compiler itself builds fine after removing the `-DLIBCXX_HAS_MUSL_LIBC=ON` flag)

**Comment by ghost** [comment]
I have successfully built `llvm` from the monorepo branch (https://github.com/konimex/kiss-llvm/commit/378875246afc171300964f61f4f88165192dce13) on a fresh install of KISS. Rebuilt some packages with `gcc` completely uninstalled and it looks like this is working fine now.

I think this is a more ideal way to go as it's a much simpler (and less error-prone) 2-step process.

The only issue I'm having now is when I tried rebuilding `busybox` it failed on some `gcc` version checking script (`busybox/scripts/gcc-version.sh`) and with:
```
/home/trb/.cache/kiss/build-208300/busybox/applets/busybox.mkll: line 15: gcc: not found
  HOSTCC  scripts/basic/fixdep
/bin/sh: gcc: not found
```
I'm going to try the wyverkiss package shortly, and assuming that works it should be repackaged here.

**Comment by dilyn-corner** [comment]
~~@trbednarzyk perhaps try setting HOSTCC=cc?~~ `busybox` itself sets this to cc if it's undefined. And the official package sets this unless it's already set... Strange that this would happen. Worth a shot mayhaps?

**Comment by ghost** [comment]
Even though the package itself sets CC and HOSTCC I did try explicitly setting them to `clang` or `cc` (which I made sure pointed to `clang`) and neither time worked.

**Comment by dilyn-corner** [comment]
Would you happen to be using `ccache`?

**Comment by ghost** [comment]
No. This was a completely fresh install of KISS and I've only installed dependencies of LLVM along with LLVM itself.

**Comment by ghost** [comment]
Well I took the wyverkiss package of `busybox` and did the following:
- Removed `gmake` from `depends` and `s/gmake/make/` in `build`
- Removed `pigz` from `depends`

This appears to have worked.

**Comment by ghost** [comment]
Looking at the busybox [Makefile](https://git.busybox.net/busybox/tree/Makefile), I can see why the issue's happening. If you go to lines 274, 275, and 292 some variables (`HOSTCC`, `HOSTCXX`, `CC`) are forcibly overwritten to be `gcc`/`g++`. I'll try building the KISS package with just a simple extra `sed -i 's/gcc/clang/;s/g++/clang++/' Makefile` tomorrow.

Why anyone would force defaults like this is beyond me.

**Comment by konimex** [comment]
Since the primary issue (failure to libc++abi) has been resolved with the new monorepo approach, I'm going to close this PR and the issue. As for busybox, perhaps we should open a separate issue or bring it up to Dylan (in the mainline kiss-repo) and think of the best approach.

**Comment by dylanaraps** [comment]
Busybox issue should be fixed here: https://github.com/kisslinux/repo/commit/b98fac2901c99d2bc0e513c5a14765267a28ec0d

Let me know if it still occurs.

**Pull request closed without merging**
